name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - BloonsTD6 Mod Helper/**
  pull_request:
    branches:
      - '*'

env:
  PROJECT_NAME: Btd6ModHelper
  BLOONSTD6: Installer/BloonsTD6

jobs:
  build:
    
    runs-on: windows-latest

    steps:
      
      # Setup Environment

      - name: Clone Repo
        uses: actions/checkout@master

      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: modders.json

      - name: Download Latest MelonLoader
        if: env.MELONLOADER_BRANCH == ''
        uses: robinraju/release-downloader@v1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: LavaGang/MelonLoader
          fileName: MelonLoader.x64.zip
          tarBall: false
          zipBall: false
          latest: true
      - name: Extract Latest MelonLoader
        if: env.MELONLOADER_BRANCH == ''
        shell: bash
        run: unzip MelonLoader.x64.zip -d ${{ env.BLOONSTD6 }}

      - name: Clone Dependencies Repo
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: doombubbles/btd6-ci-dependencies
          ref: main
          path: ${{ env.BLOONSTD6 }}/MelonLoader/Il2CppAssemblies

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x


      # Build Mod Helper

      - name: Build BloonsTD6 Mod Helper
        run: dotnet build -c Release "./BloonsTD6 Mod Helper/BloonsTD6 Mod Helper.csproj" -p:BloonsTD6="../${{ env.BLOONSTD6 }}"

      - name: Upload Mod DLL
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}.dll
          path: ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}.dll

      - name: Upload Mod Documentation
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}.xml
          path: ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}.xml


      # Build Installer

      - name: Install Wix
        run: dotnet tool install --global wix

      - name: Download dotNet 6.0 Installer
        shell: bash
        run: C:/msys64/usr/bin/wget.exe -O Installer/windowsdesktop-runtime-6.0.29-win-x64.exe https://download.visualstudio.microsoft.com/download/pr/d0849e66-227d-40f7-8f7b-c3f7dfe51f43/37f8a04ab7ff94db7f20d3c598dc4d74/windowsdesktop-runtime-6.0.29-win-x64.exe

      - name: Clear Il2CppAssemblies
        shell: bash
        run: rm -rf ${{ env.BLOONSTD6 }}/MelonLoader/Il2CppAssemblies

      - name: Build Installer Steam
        run: dotnet build -c Installer /p:Platform=Steam "./Installer/Installer.csproj"

      - name: Upload Steam Installer
        uses: actions/upload-artifact@v3
        with:
          name: InstallBtd6ModHelperSteam.exe
          path: Installer/InstallBtd6ModHelperSteam.exe

      - name: Download BTD6EpicGamesModCompat
        uses: robinraju/release-downloader@v1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: GrahamKracker/BTD6EpicGamesModCompat
          fileName: BTD6EpicGamesModCompat.dll
          tarBall: false
          zipBall: false
          latest: true
          out-file-path: ${{ env.BLOONSTD6 }}/Plugins

      - name: Build Installer Epic
        run: dotnet build -c Installer /p:Platform=Epic "./Installer/Installer.csproj"

      - name: Upload Epic Installer
        uses: actions/upload-artifact@v3
        with:
          name: InstallBtd6ModHelperEpic.exe
          path: Installer/InstallBtd6ModHelperEpic.exe

      # Publish Release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}.dll
            ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}.xml
            Installer/InstallBtd6ModHelperSteam.exe
            Installer/InstallBtd6ModHelperEpic.exe
          body_path: ./BloonsTD6 Mod Helper/LATEST.md
          fail_on_unmatched_files: true
